CREATE TABLE IF NOT EXISTS ADDR_OBJ_ZIP_CODE
(
REGION   BIGINT,
ADDR_OBJECTID BIGINT,
LEVEL    BIGINT,
ZIP_CODE    TEXT,
TYPENAME TEXT,
NAME     TEXT
)
PARTITION BY LIST (REGION);

/*CREATE INDEX ADDR_OBJ_ZIP_CODE_REGION_ADDR_OBJECTID_ix
ON ZIP_CODE (REGION,ADDR_OBJECTID);*/
