CREATE TABLE IF NOT EXISTS HOUSES_ZIP_CODE
(
REGION   BIGINT,
H_OBJECTID BIGINT,

ADDR_OBJECTID BIGINT,
LEVEL    BIGINT,
ZIP_CODE    TEXT,
TYPENAME TEXT,
NAME     TEXT,

HOUSETYPE TEXT,
HOUSENUM TEXT,
ADDTYPE1 TEXT,
ADDNUM1 TEXT,
ADDTYPE2 TEXT,
ADDNUM2 TEXT
)
PARTITION BY LIST (REGION);

/*CREATE INDEX HOUSES_ZIP_CODE_REGION_H_OBJECTID_ix
ON ZIP_CODE (region,h_objectid);*/
