CREATE TABLE IF NOT EXISTS HOUSES_ZIP_CODE<?= $suffix ?>
(
REGION   BIGINT,
H_OBJECTID BIGINT,

ADDR_OBJECTID BIGINT,
LEVEL    BIGINT,
ZIP_CODE    TEXT,
TYPENAME TEXT,
NAME     TEXT,

HOUSETYPE TEXT,
HOUSENUM TEXT,
ADDTYPE1 TEXT,
ADDNUM1 TEXT,
ADDTYPE2 TEXT,
ADDNUM2 TEXT
);

/*CREATE INDEX HOUSES_ZIP_CODE<?= $suffix ?>_REGION_H_OBJECTID_ix
ON ZIP_CODE<?= $suffix ?> (REGION,h_objectid);*/

ALTER TABLE HOUSES_ZIP_CODE
ATTACH PARTITION HOUSES_ZIP_CODE<?= $suffix ?> FOR
VALUES IN (<?= $suffix ?>);
