CREATE INDEX ADM_HIERARCHY<?= $suffix ?>_REGION_OBJECTID_ISACTIVE_IX
ON ADM_HIERARCHY<?= $suffix ?> (REGION,OBJECTID,ISACTIVE);
CREATE INDEX ADM_HIERARCHY<?= $suffix ?>_REGION_PARENTOBJID_IX
ON ADM_HIERARCHY<?= $suffix ?> (REGION,PARENTOBJID);
